<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

/**
 * Language strings for local_web3talents.
 *
 * @package    local_web3talents
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'Web3 Talents';
$string['settings'] = 'Web3 Talents settings';
$string['setting_enabled'] = 'Enable Web3 Talents workflows';
$string['setting_enabled_desc'] = 'Controls whether custom Web3 Talents workflows should be available once implemented.';
$string['setting_fundamentals_course_shortname'] = 'Fundamentals course shortname';
$string['setting_fundamentals_course_shortname_desc'] = 'Moodle course shortname used by Web3 Talents workflows.';
$string['dashboard_intro'] = 'This plugin will manage accepted applicants, student account creation, room generation, mentor/student room visibility, and Zoom CSV exports.';
$string['dashboard_status_enabled'] = 'Workflows enabled';
$string['dashboard_status_disabled'] = 'Workflows disabled';
$string['dashboard_course_shortname'] = 'Fundamentals course';
$string['dashboard_next_steps'] = 'Next implementation steps';
$string['dashboard_next_applicants'] = 'Accepted-applicant list and account creation';
$string['dashboard_next_policy'] = 'First-login policy agreement';
$string['dashboard_next_rooms'] = 'Topic-based room generation and exports';
$string['privacy:metadata'] = 'The Web3 Talents plugin scaffold does not currently store personal data beyond the Moodle operational event log table.';
$string['privacy:metadata:local_web3talents_log'] = 'Stores operational events generated by Web3 Talents plugin workflows.';
$string['privacy:metadata:local_web3talents_log:userid'] = 'The user associated with an operational event, when applicable.';
$string['privacy:metadata:local_web3talents_log:courseid'] = 'The course associated with an operational event, when applicable.';
$string['privacy:metadata:local_web3talents_log:eventtype'] = 'The type of operational event.';
$string['privacy:metadata:local_web3talents_log:metadata'] = 'Structured event details.';
$string['privacy:metadata:local_web3talents_log:timecreated'] = 'The time the operational event was recorded.';
